# Generated by Django 5.1.7 on 2025-03-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rol_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=45)),
                ('sueldo', models.FloatField(null=True)),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abasto.rol_usuario')),
            ],
        ),
    ]
