import string

class nameSP():
    loginUsuario = 'GetUsuario'
    registrarUsuario = 'SetUsuario'
    agregarProducto = 'SetProducto'
    obtenerProducto = 'GetProducto'
    obtenerCategoria = 'GetCategorias'
    obtenerEstados = 'GetEstados'
    agregarCategoria = 'SetCategoria'
    agregarMarca = 'SetMarca'
    obtenerMarca = 'GetMarca'
    agregarUnidad = 'SetUnidadMedida'
    obtenerUnidad = 'GetUnidadMedida'
    agregarProveedor = 'SetProveedor'
    obtenerProveedor = 'GetProveedor'
    agregarPrecio = 'SetPrecio'
    obtenerPrecio = 'GetPrecio'
    obtenerRol = 'GetRol'
    obtenerMedidasConversion = 'GetMedidasConversion'
    agregarMedidaConversion = 'SetMedidaConversion'
    agregarStockProducto = 'SetStockProducto'
    obtenerStockProducto = 'GetStockProducto'
    agregarIva = 'SetIva'
    obtenerIva = 'GetIva'
    agregarPedido = 'SetPedido'
    agregarDetallePedido = 'SetDetallePedido'
    obtenerDetallePedido = 'GetDetallePedido'
    obtenerPedido = 'GetPedido'
    agregarFactura = 'SetFactura'
    agregarDetalleFactura = 'SetDetalleFactura'
    agregarCliente = 'SetCliente'
    obtenerCliente = 'GetCliente'
    obtenerReportes = 'GetReportes'
    agregarRol = 'SetRol'